#!/usr/bin/env python3

import z3
from z3 import Or

solver = z3.Solver()

variables = {}

for i in range(1, 51):
    var_name = f'v{i}'
    variables[var_name] = z3.Int(var_name)
    solver.add(variables[var_name] >= 0)
    solver.add(variables[var_name] <= 1)

solver.add(Or(Or(variables["v3"] == 0, variables["v36"] == 1), variables["v7"] == 1))
solver.add(Or(Or(variables["v3"] == 0, variables["v42"] == 0), variables["v48"] == 0))
solver.add(Or(Or(variables["v49"] == 0, variables["v47"] == 0), variables["v41"] == 0))
solver.add(Or(Or(variables["v8"] == 1, variables["v40"] == 0), variables["v17"] == 1))
solver.add(Or(Or(variables["v21"] == 0, variables["v31"] == 0), variables["v39"] == 0))
solver.add(Or(Or(variables["v36"] == 1, variables["v22"] == 0), variables["v49"] == 1))
solver.add(Or(Or(variables["v27"] == 1, variables["v38"] == 1), variables["v14"] == 1))
solver.add(Or(Or(variables["v15"] == 1, variables["v18"] == 0), variables["v6"] == 1))
solver.add(Or(Or(variables["v6"] == 1, variables["v7"] == 1), variables["v43"] == 0))
solver.add(Or(Or(variables["v34"] == 1, variables["v7"] == 0), variables["v23"] == 1))
solver.add(Or(Or(variables["v2"] == 1, variables["v14"] == 1), variables["v13"] == 0))
solver.add(Or(Or(variables["v2"] == 1, variables["v47"] == 1), variables["v42"] == 0))
solver.add(Or(Or(variables["v33"] == 0, variables["v35"] == 0), variables["v3"] == 1))
solver.add(Or(Or(variables["v44"] == 1, variables["v40"] == 1), variables["v49"] == 1))
solver.add(Or(Or(variables["v50"] == 1, variables["v36"] == 1), variables["v31"] == 1))
solver.add(Or(Or(variables["v36"] == 0, variables["v3"] == 0), variables["v37"] == 0))
solver.add(Or(Or(variables["v26"] == 1, variables["v29"] == 0), variables["v43"] == 1))
solver.add(Or(Or(variables["v15"] == 1, variables["v29"] == 1), variables["v45"] == 0))
solver.add(Or(Or(variables["v24"] == 1, variables["v11"] == 0), variables["v18"] == 1))
solver.add(Or(Or(variables["v47"] == 0, variables["v26"] == 0), variables["v6"] == 1))
solver.add(Or(Or(variables["v50"] == 0, variables["v33"] == 0), variables["v10"] == 0))
solver.add(Or(Or(variables["v32"] == 1, variables["v6"] == 1), variables["v16"] == 1))
solver.add(Or(Or(variables["v34"] == 0, variables["v37"] == 1), variables["v41"] == 1))
solver.add(Or(Or(variables["v7"] == 1, variables["v28"] == 0), variables["v17"] == 0))
solver.add(Or(Or(variables["v44"] == 0, variables["v46"] == 1), variables["v19"] == 1))
solver.add(Or(Or(variables["v7"] == 1, variables["v22"] == 1), variables["v48"] == 0))
solver.add(Or(Or(variables["v3"] == 1, variables["v39"] == 1), variables["v34"] == 1))
solver.add(Or(Or(variables["v31"] == 1, variables["v46"] == 1), variables["v43"] == 0))
solver.add(Or(Or(variables["v27"] == 0, variables["v32"] == 1), variables["v23"] == 1))
solver.add(Or(Or(variables["v37"] == 1, variables["v50"] == 0), variables["v18"] == 0))
solver.add(Or(Or(variables["v20"] == 1, variables["v5"] == 1), variables["v11"] == 1))
solver.add(Or(Or(variables["v45"] == 0, variables["v24"] == 0), variables["v6"] == 1))
solver.add(Or(Or(variables["v34"] == 0, variables["v23"] == 0), variables["v14"] == 0))
solver.add(Or(Or(variables["v22"] == 0, variables["v21"] == 1), variables["v20"] == 1))
solver.add(Or(Or(variables["v17"] == 0, variables["v50"] == 1), variables["v24"] == 1))
solver.add(Or(Or(variables["v25"] == 0, variables["v24"] == 0), variables["v27"] == 0))
solver.add(Or(Or(variables["v3"] == 1, variables["v35"] == 1), variables["v21"] == 1))
solver.add(Or(Or(variables["v26"] == 0, variables["v47"] == 1), variables["v36"] == 0))
solver.add(Or(Or(variables["v28"] == 0, variables["v45"] == 0), variables["v49"] == 1))
solver.add(Or(Or(variables["v21"] == 0, variables["v6"] == 0), variables["v12"] == 1))
solver.add(Or(Or(variables["v17"] == 0, variables["v15"] == 0), variables["v39"] == 0))
solver.add(Or(Or(variables["v41"] == 1, variables["v2"] == 1), variables["v14"] == 0))
solver.add(Or(Or(variables["v25"] == 1, variables["v36"] == 1), variables["v23"] == 0))
solver.add(Or(Or(variables["v39"] == 0, variables["v3"] == 0), variables["v40"] == 0))
solver.add(Or(Or(variables["v50"] == 1, variables["v20"] == 1), variables["v35"] == 1))
solver.add(Or(Or(variables["v27"] == 1, variables["v31"] == 1), variables["v39"] == 0))
solver.add(Or(Or(variables["v45"] == 1, variables["v15"] == 0), variables["v40"] == 0))
solver.add(Or(Or(variables["v34"] == 1, variables["v50"] == 1), variables["v35"] == 1))
solver.add(Or(Or(variables["v1"] == 0, variables["v48"] == 0), variables["v12"] == 1))
solver.add(Or(Or(variables["v18"] == 1, variables["v35"] == 0), variables["v30"] == 0))
solver.add(Or(Or(variables["v27"] == 1, variables["v24"] == 0), variables["v25"] == 0))
solver.add(Or(Or(variables["v4"] == 0, variables["v33"] == 0), variables["v12"] == 0))
solver.add(Or(Or(variables["v43"] == 0, variables["v24"] == 0), variables["v37"] == 0))
solver.add(Or(Or(variables["v37"] == 0, variables["v31"] == 1), variables["v44"] == 0))
solver.add(Or(Or(variables["v9"] == 0, variables["v38"] == 0), variables["v14"] == 1))
solver.add(Or(Or(variables["v33"] == 1, variables["v16"] == 0), variables["v34"] == 1))
solver.add(Or(Or(variables["v4"] == 1, variables["v35"] == 0), variables["v5"] == 0))
solver.add(Or(Or(variables["v3"] == 0, variables["v21"] == 0), variables["v19"] == 0))
solver.add(Or(Or(variables["v35"] == 0, variables["v36"] == 0), variables["v29"] == 0))
solver.add(Or(Or(variables["v7"] == 1, variables["v43"] == 0), variables["v36"] == 1))
solver.add(Or(Or(variables["v30"] == 1, variables["v14"] == 1), variables["v41"] == 1))
solver.add(Or(Or(variables["v35"] == 0, variables["v24"] == 0), variables["v7"] == 0))
solver.add(Or(Or(variables["v35"] == 1, variables["v42"] == 0), variables["v6"] == 1))
solver.add(Or(Or(variables["v1"] == 0, variables["v15"] == 0), variables["v39"] == 1))
solver.add(Or(Or(variables["v27"] == 1, variables["v49"] == 1), variables["v16"] == 0))
solver.add(Or(Or(variables["v37"] == 0, variables["v49"] == 1), variables["v10"] == 0))
solver.add(Or(Or(variables["v50"] == 1, variables["v46"] == 0), variables["v3"] == 0))
solver.add(Or(Or(variables["v41"] == 0, variables["v20"] == 1), variables["v34"] == 1))
solver.add(Or(Or(variables["v1"] == 0, variables["v23"] == 1), variables["v28"] == 1))
solver.add(Or(Or(variables["v12"] == 0, variables["v30"] == 0), variables["v20"] == 0))
solver.add(Or(Or(variables["v24"] == 0, variables["v29"] == 1), variables["v37"] == 0))
solver.add(Or(Or(variables["v12"] == 1, variables["v5"] == 1), variables["v44"] == 0))
solver.add(Or(Or(variables["v6"] == 0, variables["v2"] == 0), variables["v48"] == 1))
solver.add(Or(Or(variables["v2"] == 0, variables["v49"] == 0), variables["v43"] == 0))
solver.add(Or(Or(variables["v1"] == 1, variables["v50"] == 0), variables["v24"] == 1))
solver.add(Or(Or(variables["v7"] == 0, variables["v50"] == 0), variables["v44"] == 0))
solver.add(Or(Or(variables["v41"] == 0, variables["v43"] == 1), variables["v4"] == 1))
solver.add(Or(Or(variables["v13"] == 1, variables["v15"] == 1), variables["v11"] == 0))
solver.add(Or(Or(variables["v3"] == 0, variables["v11"] == 0), variables["v23"] == 1))
solver.add(Or(Or(variables["v33"] == 1, variables["v48"] == 1), variables["v41"] == 1))
solver.add(Or(Or(variables["v9"] == 1, variables["v23"] == 1), variables["v49"] == 0))
solver.add(Or(Or(variables["v43"] == 0, variables["v47"] == 1), variables["v1"] == 1))
solver.add(Or(Or(variables["v40"] == 0, variables["v16"] == 1), variables["v29"] == 0))
solver.add(Or(Or(variables["v30"] == 1, variables["v19"] == 1), variables["v3"] == 1))
solver.add(Or(Or(variables["v19"] == 1, variables["v34"] == 0), variables["v48"] == 1))
solver.add(Or(Or(variables["v16"] == 0, variables["v44"] == 0), variables["v14"] == 1))
solver.add(Or(Or(variables["v38"] == 1, variables["v45"] == 0), variables["v12"] == 0))
solver.add(Or(Or(variables["v4"] == 0, variables["v14"] == 0), variables["v31"] == 0))
solver.add(Or(Or(variables["v48"] == 0, variables["v35"] == 1), variables["v1"] == 0))
solver.add(Or(Or(variables["v45"] == 1, variables["v13"] == 0), variables["v19"] == 1))
solver.add(Or(Or(variables["v9"] == 1, variables["v42"] == 1), variables["v7"] == 0))
solver.add(Or(Or(variables["v1"] == 0, variables["v15"] == 0), variables["v8"] == 1))
solver.add(Or(Or(variables["v13"] == 0, variables["v44"] == 0), variables["v14"] == 0))
solver.add(Or(Or(variables["v43"] == 0, variables["v37"] == 0), variables["v31"] == 0))
solver.add(Or(Or(variables["v27"] == 0, variables["v29"] == 0), variables["v47"] == 1))
solver.add(Or(Or(variables["v7"] == 1, variables["v4"] == 1), variables["v17"] == 1))
solver.add(Or(Or(variables["v7"] == 1, variables["v10"] == 1), variables["v35"] == 1))
solver.add(Or(Or(variables["v25"] == 0, variables["v20"] == 1), variables["v17"] == 1))
solver.add(Or(Or(variables["v35"] == 1, variables["v5"] == 0), variables["v42"] == 0))
solver.add(Or(Or(variables["v50"] == 0, variables["v24"] == 1), variables["v5"] == 0))
solver.add(Or(Or(variables["v21"] == 0, variables["v26"] == 0), variables["v2"] == 1))
solver.add(Or(Or(variables["v8"] == 0, variables["v45"] == 1), variables["v21"] == 0))
solver.add(Or(Or(variables["v16"] == 0, variables["v33"] == 1), variables["v49"] == 1))
solver.add(Or(Or(variables["v38"] == 0, variables["v6"] == 1), variables["v16"] == 1))
solver.add(Or(Or(variables["v5"] == 1, variables["v21"] == 1), variables["v37"] == 1))
solver.add(Or(Or(variables["v8"] == 1, variables["v38"] == 1), variables["v31"] == 1))
solver.add(Or(Or(variables["v21"] == 0, variables["v33"] == 1), variables["v14"] == 1))
solver.add(Or(Or(variables["v20"] == 1, variables["v40"] == 1), variables["v5"] == 0))
solver.add(Or(Or(variables["v29"] == 0, variables["v9"] == 0), variables["v31"] == 1))
solver.add(Or(Or(variables["v7"] == 0, variables["v42"] == 1), variables["v22"] == 0))
solver.add(Or(Or(variables["v48"] == 0, variables["v8"] == 1), variables["v26"] == 1))
solver.add(Or(Or(variables["v48"] == 1, variables["v38"] == 0), variables["v33"] == 1))
solver.add(Or(Or(variables["v34"] == 0, variables["v49"] == 1), variables["v46"] == 1))
solver.add(Or(Or(variables["v14"] == 0, variables["v46"] == 0), variables["v25"] == 1))
solver.add(Or(Or(variables["v46"] == 0, variables["v4"] == 1), variables["v18"] == 1))
solver.add(Or(Or(variables["v36"] == 1, variables["v12"] == 0), variables["v31"] == 0))
solver.add(Or(Or(variables["v12"] == 1, variables["v18"] == 0), variables["v14"] == 1))
solver.add(Or(Or(variables["v7"] == 0, variables["v46"] == 1), variables["v16"] == 0))
solver.add(Or(Or(variables["v9"] == 1, variables["v8"] == 0), variables["v7"] == 1))
solver.add(Or(Or(variables["v49"] == 1, variables["v42"] == 0), variables["v22"] == 0))
solver.add(Or(Or(variables["v22"] == 1, variables["v15"] == 0), variables["v38"] == 1))
solver.add(Or(Or(variables["v34"] == 1, variables["v41"] == 0), variables["v47"] == 1))
solver.add(Or(Or(variables["v22"] == 1, variables["v26"] == 0), variables["v32"] == 1))
solver.add(Or(Or(variables["v25"] == 0, variables["v45"] == 0), variables["v21"] == 0))
solver.add(Or(Or(variables["v26"] == 0, variables["v32"] == 1), variables["v11"] == 0))
solver.add(Or(Or(variables["v15"] == 1, variables["v26"] == 1), variables["v25"] == 0))
solver.add(Or(Or(variables["v1"] == 0, variables["v46"] == 1), variables["v25"] == 1))
solver.add(Or(Or(variables["v14"] == 0, variables["v31"] == 0), variables["v30"] == 1))
solver.add(Or(Or(variables["v9"] == 0, variables["v22"] == 0), variables["v12"] == 1))
solver.add(Or(Or(variables["v18"] == 0, variables["v26"] == 1), variables["v35"] == 0))
solver.add(Or(Or(variables["v16"] == 0, variables["v32"] == 0), variables["v21"] == 0))
solver.add(Or(Or(variables["v31"] == 1, variables["v49"] == 0), variables["v21"] == 0))
solver.add(Or(Or(variables["v11"] == 1, variables["v9"] == 1), variables["v41"] == 1))
solver.add(Or(Or(variables["v13"] == 0, variables["v30"] == 0), variables["v19"] == 1))
solver.add(Or(Or(variables["v10"] == 0, variables["v4"] == 1), variables["v6"] == 1))
solver.add(Or(Or(variables["v4"] == 0, variables["v3"] == 1), variables["v22"] == 0))
solver.add(Or(Or(variables["v25"] == 0, variables["v50"] == 0), variables["v18"] == 0))
solver.add(Or(Or(variables["v40"] == 0, variables["v4"] == 1), variables["v9"] == 1))
solver.add(Or(Or(variables["v37"] == 1, variables["v20"] == 1), variables["v46"] == 1))
solver.add(Or(Or(variables["v27"] == 0, variables["v22"] == 1), variables["v29"] == 0))
solver.add(Or(Or(variables["v34"] == 1, variables["v14"] == 1), variables["v3"] == 1))
solver.add(Or(Or(variables["v3"] == 1, variables["v31"] == 0), variables["v20"] == 1))
solver.add(Or(Or(variables["v50"] == 0, variables["v2"] == 1), variables["v26"] == 0))
solver.add(Or(Or(variables["v17"] == 1, variables["v29"] == 0), variables["v38"] == 1))
solver.add(Or(Or(variables["v49"] == 0, variables["v12"] == 1), variables["v41"] == 0))
solver.add(Or(Or(variables["v15"] == 1, variables["v35"] == 0), variables["v43"] == 0))
solver.add(Or(Or(variables["v22"] == 0, variables["v23"] == 0), variables["v49"] == 0))
solver.add(Or(Or(variables["v9"] == 0, variables["v33"] == 1), variables["v48"] == 1))
solver.add(Or(Or(variables["v26"] == 1, variables["v29"] == 1), variables["v35"] == 1))
solver.add(Or(Or(variables["v27"] == 1, variables["v50"] == 0), variables["v37"] == 1))
solver.add(Or(Or(variables["v7"] == 0, variables["v46"] == 1), variables["v43"] == 0))
solver.add(Or(Or(variables["v46"] == 0, variables["v37"] == 0), variables["v8"] == 0))
solver.add(Or(Or(variables["v40"] == 0, variables["v36"] == 1), variables["v24"] == 0))
solver.add(Or(Or(variables["v44"] == 0, variables["v46"] == 1), variables["v15"] == 1))
solver.add(Or(Or(variables["v3"] == 0, variables["v36"] == 1), variables["v16"] == 0))
solver.add(Or(Or(variables["v48"] == 0, variables["v9"] == 1), variables["v43"] == 1))
solver.add(Or(Or(variables["v25"] == 0, variables["v4"] == 0), variables["v44"] == 1))
solver.add(Or(Or(variables["v22"] == 0, variables["v37"] == 1), variables["v7"] == 0))
solver.add(Or(Or(variables["v31"] == 0, variables["v17"] == 0), variables["v22"] == 0))
solver.add(Or(Or(variables["v11"] == 0, variables["v48"] == 0), variables["v17"] == 1))
solver.add(Or(Or(variables["v23"] == 1, variables["v34"] == 1), variables["v28"] == 0))
solver.add(Or(Or(variables["v23"] == 1, variables["v48"] == 0), variables["v39"] == 0))
solver.add(Or(Or(variables["v37"] == 0, variables["v1"] == 0), variables["v23"] == 0))
solver.add(Or(Or(variables["v19"] == 0, variables["v27"] == 1), variables["v14"] == 1))
solver.add(Or(Or(variables["v22"] == 0, variables["v33"] == 1), variables["v6"] == 0))
solver.add(Or(Or(variables["v6"] == 0, variables["v32"] == 0), variables["v26"] == 0))
solver.add(Or(Or(variables["v18"] == 1, variables["v20"] == 0), variables["v46"] == 0))
solver.add(Or(Or(variables["v43"] == 1, variables["v22"] == 1), variables["v27"] == 1))
solver.add(Or(Or(variables["v13"] == 0, variables["v34"] == 1), variables["v49"] == 1))
solver.add(Or(Or(variables["v35"] == 0, variables["v46"] == 0), variables["v3"] == 1))
solver.add(Or(Or(variables["v32"] == 1, variables["v39"] == 1), variables["v43"] == 0))
solver.add(Or(Or(variables["v6"] == 1, variables["v39"] == 0), variables["v9"] == 0))
solver.add(Or(Or(variables["v27"] == 1, variables["v39"] == 1), variables["v16"] == 0))
solver.add(Or(Or(variables["v25"] == 1, variables["v17"] == 0), variables["v15"] == 0))
solver.add(Or(Or(variables["v43"] == 0, variables["v27"] == 1), variables["v34"] == 1))
solver.add(Or(Or(variables["v6"] == 0, variables["v49"] == 1), variables["v5"] == 1))
solver.add(Or(Or(variables["v38"] == 0, variables["v11"] == 1), variables["v14"] == 1))
solver.add(Or(Or(variables["v40"] == 1, variables["v38"] == 0), variables["v47"] == 1))
solver.add(Or(Or(variables["v37"] == 1, variables["v14"] == 0), variables["v17"] == 1))
solver.add(Or(Or(variables["v39"] == 1, variables["v29"] == 1), variables["v36"] == 1))
solver.add(Or(Or(variables["v39"] == 0, variables["v28"] == 0), variables["v1"] == 1))
solver.add(Or(Or(variables["v18"] == 0, variables["v14"] == 1), variables["v16"] == 0))
solver.add(Or(Or(variables["v40"] == 0, variables["v50"] == 1), variables["v15"] == 1))
solver.add(Or(Or(variables["v37"] == 1, variables["v42"] == 0), variables["v18"] == 1))
solver.add(Or(Or(variables["v13"] == 0, variables["v31"] == 1), variables["v33"] == 1))
solver.add(Or(Or(variables["v2"] == 1, variables["v42"] == 0), variables["v33"] == 1))
solver.add(Or(Or(variables["v8"] == 1, variables["v3"] == 0), variables["v22"] == 0))
solver.add(Or(Or(variables["v1"] == 1, variables["v23"] == 1), variables["v31"] == 0))
solver.add(Or(Or(variables["v20"] == 0, variables["v45"] == 0), variables["v26"] == 1))
solver.add(Or(Or(variables["v42"] == 1, variables["v11"] == 1), variables["v49"] == 1))
solver.add(Or(Or(variables["v29"] == 1, variables["v11"] == 1), variables["v43"] == 0))
solver.add(Or(Or(variables["v20"] == 0, variables["v21"] == 0), variables["v30"] == 1))
solver.add(Or(Or(variables["v23"] == 1, variables["v45"] == 1), variables["v35"] == 0))
solver.add(Or(Or(variables["v38"] == 1, variables["v30"] == 0), variables["v14"] == 0))
solver.add(Or(Or(variables["v9"] == 0, variables["v48"] == 1), variables["v29"] == 0))
solver.add(Or(Or(variables["v11"] == 1, variables["v18"] == 0), variables["v23"] == 0))
solver.add(Or(Or(variables["v41"] == 0, variables["v1"] == 0), variables["v29"] == 0))
solver.add(Or(Or(variables["v5"] == 1, variables["v41"] == 1), variables["v26"] == 1))
solver.add(Or(Or(variables["v44"] == 1, variables["v30"] == 0), variables["v7"] == 0))
solver.add(Or(Or(variables["v38"] == 1, variables["v6"] == 0), variables["v41"] == 0))
solver.add(Or(Or(variables["v46"] == 1, variables["v48"] == 1), variables["v15"] == 0))
solver.add(Or(Or(variables["v18"] == 0, variables["v10"] == 0), variables["v47"] == 0))
solver.add(Or(Or(variables["v38"] == 1, variables["v46"] == 1), variables["v32"] == 0))
solver.add(Or(Or(variables["v32"] == 0, variables["v46"] == 1), variables["v12"] == 1))
solver.add(Or(Or(variables["v31"] == 1, variables["v40"] == 1), variables["v14"] == 1))
solver.add(Or(Or(variables["v18"] == 0, variables["v2"] == 1), variables["v49"] == 1))
solver.add(Or(Or(variables["v28"] == 1, variables["v38"] == 0), variables["v27"] == 1))
solver.add(Or(Or(variables["v16"] == 0, variables["v21"] == 0), variables["v14"] == 1))
solver.add(Or(Or(variables["v29"] == 0, variables["v15"] == 1), variables["v12"] == 1))
solver.add(Or(Or(variables["v49"] == 1, variables["v34"] == 1), variables["v5"] == 1))
solver.add(Or(Or(variables["v14"] == 1, variables["v22"] == 1), variables["v12"] == 0))
solver.add(Or(Or(variables["v30"] == 1, variables["v33"] == 1), variables["v20"] == 1))
solver.add(Or(Or(variables["v24"] == 0, variables["v22"] == 1), variables["v25"] == 1))
solver.add(Or(Or(variables["v4"] == 1, variables["v48"] == 0), variables["v23"] == 0))
solver.add(Or(Or(variables["v30"] == 0, variables["v36"] == 0), variables["v9"] == 1))
solver.add(Or(Or(variables["v44"] == 1, variables["v12"] == 1), variables["v35"] == 0))
solver.add(Or(Or(variables["v38"] == 1, variables["v3"] == 1), variables["v21"] == 0))
solver.add(Or(Or(variables["v11"] == 0, variables["v33"] == 1), variables["v49"] == 1))

result = solver.check()

solutions = []

while (result == z3.sat):
    res = solver.model()
    ans = ""

    next_expr = ""
    for i in range(1, 51):
        var_name = f'v{i}'
        digit = res[variables[var_name]]
        ans = f'{digit}{ans}'
        if next_expr != "":
            next_expr = f'{next_expr}, '
        next_expr = f'{next_expr}variables["{var_name}"] != {res[variables[var_name]]}'

    solutions.append(ans)
    next_expr = f'solver.add(Or({next_expr}))'
    # print(next_expr)
    eval(next_expr)
    result = solver.check()

solutions.sort()

for solution in solutions:
    print(solution)
