#!/usr/bin/env python3

import z3
from z3 import Or

solver = z3.Solver()

variables = {}

for i in range(1, 41):
    var_name = f'v{i}'
    variables[var_name] = z3.Int(var_name)
    solver.add(variables[var_name] >= 0)
    solver.add(variables[var_name] <= 1)

solver.add(Or(variables["v18"] == 0, variables["v15"] == 0))
solver.add(Or(variables["v14"] == 0, variables["v9"] == 0))
solver.add(Or(Or(variables["v19"] == 0, variables["v37"] == 1), variables["v12"] == 1))
solver.add(variables["v39"] == 0)
solver.add(Or(variables["v20"] == 0, variables["v18"] == 1))
solver.add(Or(Or(variables["v8"] == 0, variables["v16"] == 1), variables["v24"] == 0))
solver.add(Or(variables["v29"] == 0, variables["v39"] == 0))
solver.add(Or(variables["v2"] == 0, variables["v19"] == 1))
solver.add(variables["v15"] == 1)
solver.add(Or(Or(variables["v37"] == 0, variables["v19"] == 1), variables["v6"] == 0))
solver.add(Or(variables["v25"] == 1, variables["v23"] == 0))
solver.add(Or(Or(variables["v17"] == 0, variables["v40"] == 1), variables["v21"] == 1))
solver.add(Or(Or(variables["v23"] == 0, variables["v35"] == 1), variables["v24"] == 1))
solver.add(Or(variables["v30"] == 0, variables["v28"] == 0))
solver.add(variables["v15"] == 1)
solver.add(Or(Or(variables["v37"] == 0, variables["v19"] == 1), variables["v6"] == 1))
solver.add(Or(variables["v3"] == 0, variables["v11"] == 0))
solver.add(Or(variables["v35"] == 0, variables["v3"] == 0))
solver.add(Or(Or(variables["v29"] == 0, variables["v39"] == 1), variables["v22"] == 1))
solver.add(Or(variables["v27"] == 0, variables["v10"] == 0))
solver.add(Or(variables["v28"] == 1, variables["v8"] == 0))
solver.add(Or(variables["v4"] == 0, variables["v39"] == 1))
solver.add(Or(variables["v10"] == 1, variables["v26"] == 1))
solver.add(Or(Or(variables["v22"] == 1, variables["v14"] == 1), variables["v15"] == 1))
solver.add(variables["v13"] == 0)
solver.add(Or(Or(variables["v36"] == 1, variables["v28"] == 1), variables["v35"] == 0))
solver.add(Or(Or(variables["v8"] == 0, variables["v16"] == 1), variables["v24"] == 1))
solver.add(Or(Or(variables["v7"] == 0, variables["v3"] == 1), variables["v40"] == 0))
solver.add(Or(Or(variables["v22"] == 1, variables["v14"] == 1), variables["v15"] == 1))
solver.add(variables["v13"] == 0)
solver.add(Or(Or(variables["v8"] == 0, variables["v16"] == 1), variables["v24"] == 1))
solver.add(Or(Or(variables["v19"] == 0, variables["v37"] == 1), variables["v12"] == 1))
solver.add(Or(variables["v10"] == 1, variables["v26"] == 0))
solver.add(Or(variables["v20"] == 0, variables["v18"] == 0))
solver.add(Or(variables["v8"] == 0, variables["v16"] == 0))
solver.add(Or(Or(variables["v3"] == 0, variables["v11"] == 1), variables["v23"] == 0))
solver.add(Or(variables["v16"] == 0, variables["v37"] == 1))
solver.add(Or(variables["v38"] == 0, variables["v11"] == 0))
solver.add(Or(Or(variables["v31"] == 0, variables["v13"] == 1), variables["v14"] == 1))
solver.add(Or(variables["v33"] == 0, variables["v19"] == 1))
solver.add(Or(Or(variables["v14"] == 0, variables["v9"] == 1), variables["v29"] == 0))
solver.add(Or(variables["v6"] == 1, variables["v16"] == 1))
solver.add(Or(Or(variables["v36"] == 1, variables["v28"] == 1), variables["v35"] == 1))
solver.add(Or(variables["v19"] == 0, variables["v37"] == 0))
solver.add(Or(variables["v5"] == 0, variables["v6"] == 1))
solver.add(Or(variables["v10"] == 1, variables["v26"] == 1))
solver.add(Or(Or(variables["v3"] == 0, variables["v11"] == 1), variables["v23"] == 1))
solver.add(Or(Or(variables["v26"] == 1, variables["v37"] == 1), variables["v16"] == 0))
solver.add(Or(Or(variables["v22"] == 1, variables["v14"] == 1), variables["v15"] == 0))
solver.add(Or(Or(variables["v25"] == 1, variables["v23"] == 1), variables["v38"] == 1))
solver.add(Or(variables["v36"] == 1, variables["v28"] == 0))
solver.add(Or(variables["v35"] == 0, variables["v3"] == 1))
solver.add(Or(Or(variables["v34"] == 0, variables["v35"] == 1), variables["v37"] == 0))
solver.add(Or(variables["v5"] == 0, variables["v6"] == 0))
solver.add(Or(variables["v33"] == 0, variables["v19"] == 0))
solver.add(Or(Or(variables["v17"] == 0, variables["v40"] == 1), variables["v21"] == 1))
solver.add(Or(Or(variables["v30"] == 0, variables["v28"] == 1), variables["v4"] == 1))
solver.add(Or(Or(variables["v34"] == 0, variables["v35"] == 1), variables["v37"] == 1))
solver.add(Or(Or(variables["v28"] == 1, variables["v8"] == 1), variables["v29"] == 1))
solver.add(variables["v21"] == 0)
solver.add(Or(Or(variables["v18"] == 0, variables["v15"] == 1), variables["v39"] == 1))
solver.add(variables["v40"] == 1)
solver.add(Or(Or(variables["v3"] == 0, variables["v11"] == 1), variables["v23"] == 1))
solver.add(Or(variables["v17"] == 0, variables["v40"] == 0))
solver.add(Or(variables["v35"] == 0, variables["v3"] == 1))
solver.add(Or(variables["v33"] == 0, variables["v19"] == 1))
solver.add(Or(Or(variables["v25"] == 1, variables["v23"] == 1), variables["v38"] == 0))
solver.add(Or(variables["v27"] == 0, variables["v10"] == 1))
solver.add(Or(Or(variables["v36"] == 1, variables["v28"] == 1), variables["v35"] == 1))
solver.add(Or(Or(variables["v7"] == 0, variables["v3"] == 1), variables["v40"] == 1))
solver.add(Or(variables["v11"] == 0, variables["v35"] == 1))
solver.add(Or(variables["v6"] == 1, variables["v16"] == 1))
solver.add(Or(Or(variables["v30"] == 0, variables["v28"] == 1), variables["v4"] == 1))
solver.add(Or(variables["v11"] == 0, variables["v35"] == 0))
solver.add(Or(variables["v32"] == 0, variables["v19"] == 1))
solver.add(Or(variables["v37"] == 0, variables["v19"] == 0))
solver.add(Or(variables["v26"] == 1, variables["v37"] == 0))
solver.add(Or(Or(variables["v30"] == 0, variables["v28"] == 1), variables["v4"] == 0))
solver.add(variables["v21"] == 0)
solver.add(Or(variables["v20"] == 0, variables["v18"] == 1))
solver.add(Or(variables["v9"] == 0, variables["v31"] == 1))
solver.add(Or(Or(variables["v28"] == 1, variables["v8"] == 1), variables["v29"] == 1))
solver.add(Or(Or(variables["v31"] == 0, variables["v13"] == 1), variables["v14"] == 0))
solver.add(Or(Or(variables["v24"] == 0, variables["v32"] == 1), variables["v35"] == 1))
solver.add(Or(variables["v12"] == 1, variables["v16"] == 1))
solver.add(Or(Or(variables["v29"] == 0, variables["v39"] == 1), variables["v22"] == 1))
solver.add(Or(Or(variables["v14"] == 0, variables["v9"] == 1), variables["v29"] == 1))
solver.add(variables["v39"] == 0)
solver.add(Or(variables["v4"] == 0, variables["v39"] == 0))
solver.add(Or(Or(variables["v37"] == 0, variables["v19"] == 1), variables["v6"] == 1))
solver.add(Or(variables["v23"] == 0, variables["v35"] == 0))
solver.add(Or(Or(variables["v29"] == 0, variables["v39"] == 1), variables["v22"] == 0))
solver.add(Or(variables["v5"] == 0, variables["v6"] == 1))
solver.add(variables["v40"] == 1)
solver.add(Or(Or(variables["v25"] == 1, variables["v23"] == 1), variables["v38"] == 1))
solver.add(Or(variables["v2"] == 0, variables["v19"] == 1))
solver.add(Or(variables["v12"] == 1, variables["v16"] == 1))
solver.add(Or(Or(variables["v23"] == 0, variables["v35"] == 1), variables["v24"] == 1))
solver.add(Or(variables["v31"] == 0, variables["v13"] == 0))
solver.add(Or(variables["v34"] == 0, variables["v35"] == 0))
solver.add(Or(variables["v32"] == 0, variables["v19"] == 1))
solver.add(Or(Or(variables["v24"] == 0, variables["v32"] == 1), variables["v35"] == 1))
solver.add(Or(Or(variables["v26"] == 1, variables["v37"] == 1), variables["v16"] == 1))
solver.add(Or(variables["v38"] == 0, variables["v11"] == 1))
solver.add(Or(variables["v16"] == 0, variables["v37"] == 1))
solver.add(Or(Or(variables["v7"] == 0, variables["v3"] == 1), variables["v40"] == 1))
solver.add(Or(variables["v4"] == 0, variables["v39"] == 1))
solver.add(Or(variables["v7"] == 0, variables["v3"] == 0))
solver.add(Or(Or(variables["v24"] == 0, variables["v32"] == 1), variables["v35"] == 0))
solver.add(Or(Or(variables["v34"] == 0, variables["v35"] == 1), variables["v37"] == 1))
solver.add(Or(variables["v11"] == 0, variables["v35"] == 1))
solver.add(variables["v1"] == 1)
solver.add(Or(variables["v27"] == 0, variables["v10"] == 1))
solver.add(Or(Or(variables["v23"] == 0, variables["v35"] == 1), variables["v24"] == 0))
solver.add(Or(Or(variables["v18"] == 0, variables["v15"] == 1), variables["v39"] == 0))
solver.add(Or(Or(variables["v19"] == 0, variables["v37"] == 1), variables["v12"] == 0))
solver.add(Or(Or(variables["v26"] == 1, variables["v37"] == 1), variables["v16"] == 1))
solver.add(Or(variables["v6"] == 1, variables["v16"] == 0))
solver.add(Or(Or(variables["v17"] == 0, variables["v40"] == 1), variables["v21"] == 0))
solver.add(Or(variables["v9"] == 0, variables["v31"] == 0))
solver.add(Or(variables["v32"] == 0, variables["v19"] == 0))
solver.add(Or(variables["v38"] == 0, variables["v11"] == 1))
solver.add(Or(variables["v9"] == 0, variables["v31"] == 1))
solver.add(Or(Or(variables["v14"] == 0, variables["v9"] == 1), variables["v29"] == 1))
solver.add(Or(Or(variables["v18"] == 0, variables["v15"] == 1), variables["v39"] == 1))
solver.add(Or(variables["v12"] == 1, variables["v16"] == 0))
solver.add(Or(variables["v16"] == 0, variables["v37"] == 0))
solver.add(Or(variables["v22"] == 1, variables["v14"] == 0))
solver.add(Or(Or(variables["v28"] == 1, variables["v8"] == 1), variables["v29"] == 0))
solver.add(variables["v1"] == 1)
solver.add(Or(variables["v24"] == 0, variables["v32"] == 0))
solver.add(Or(variables["v2"] == 0, variables["v19"] == 0))
solver.add(Or(Or(variables["v31"] == 0, variables["v13"] == 1), variables["v14"] == 1))

result = solver.check()

while (result == z3.sat):
    res = solver.model()
    ans = ""

    next_expr = ""
    for i in range(1, 41):
        var_name = f'v{i}'
        digit = res[variables[var_name]]
        ans = f'{digit}{ans}'
        if next_expr != "":
            next_expr = f'{next_expr}, '
        next_expr = f'{next_expr}variables["{var_name}"] != {res[variables[var_name]]}'

    print(ans)
    next_expr = f'solver.add(Or({next_expr}))'
    # print(next_expr)
    eval(next_expr)
    result = solver.check()
